name: rosetta-kaia DEV workflow
on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: download dependencies
        run: |
          go get ./...
      - name: check lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=4m 
          skip-pkg-cache: true
            # --skip-dirs=/home/runner/go/pkg/mod
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
  check-format: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: check format
        run: |
          make check-format
  check-license: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: check license
        run: |
          make check-license
  check-spell: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: install dependency
        run: |
          go mod download github.com/client9/misspell
      - name: check spell
        run: |
          make spellcheck
  check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: build test
        run: |
          go get -u go4.org/unsafe/assume-no-moving-gc
          make test
